# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteinerEscaneado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11)),
                ('pub_date', models.DateTimeField(verbose_name='Data de registro')),
                ('arqimagem', models.CharField(max_length=50)),
                ('codigoplano', models.BinaryField(verbose_name=800)),
            ],
        ),
        migrations.CreateModel(
            name='FonteImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='Data de registro')),
            ],
        ),
    ]
