# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteinerescaneado',
            name='fonte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='busca.FonteImagem'),
            preserve_default=False,
        ),
    ]
