# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0002_conteinerescaneado_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='codigoplano',
            field=models.BinaryField(verbose_name=900),
        ),
    ]
