# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0003_auto_20170705_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='codigoplano',
            field=models.CharField(max_length=800),
        ),
    ]
