# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0009_auto_20170705_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonteimagem',
            name='caminho',
            field=models.CharField(max_length=200),
        ),
    ]
