# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0010_auto_20170705_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteinerescaneado',
            name='arqimagemoriginal',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='conteinerescaneado',
            name='truckid',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='arqimagem',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
