# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0011_auto_20170706_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='codigoplano',
            field=models.BinaryField(max_length=1000, null=True),
        ),
    ]
