# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0012_auto_20170706_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conteinerescaneado',
            unique_together=set([('numero', 'pub_date')]),
        ),
        migrations.AddIndex(
            model_name='conteinerescaneado',
            index=models.Index(fields=['numero'], name='busca_conte_numero_01fbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='conteinerescaneado',
            index=models.Index(fields=['pub_date'], name='busca_conte_pub_dat_8bd43e_idx'),
        ),
        migrations.AddIndex(
            model_name='conteinerescaneado',
            index=models.Index(fields=['truckid'], name='busca_conte_truckid_d6a602_idx'),
        ),
    ]
