# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0013_auto_20170706_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascarafiltro', models.CharField(max_length=20)),
                ('diaspararepetir', models.IntegerField()),
                ('proximocarregamento', models.DateTimeField(verbose_name='Data do próximo agendamento')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.FonteImagem')),
            ],
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['proximocarregamento'], name='busca_agend_proximo_1c4cab_idx'),
        ),
    ]
