# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0014_auto_20170709_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteinerescaneado',
            name='login',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='mascarafiltro',
            field=models.CharField(max_length=20, verbose_name='Mascara no formato "%Y%m%d" mais qualquer literal'),
        ),
        migrations.AddIndex(
            model_name='conteinerescaneado',
            index=models.Index(fields=['login'], name='busca_conte_login_7fc817_idx'),
        ),
    ]
