# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0019_auto_20170807_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteinerescaneado',
            name='alerta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='conteinerescaneado',
            index=models.Index(fields=['alerta'], name='busca_conte_alerta_d374b2_idx'),
        ),
    ]
