# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0020_auto_20170816_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='alerta',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
