# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0021_auto_20170904_2141'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conteinerescaneado',
            name='busca_conte_login_7fc817_idx',
        ),
        migrations.RemoveIndex(
            model_name='conteinerescaneado',
            name='busca_conte_alerta_d374b2_idx',
        ),
        migrations.RemoveField(
            model_name='conteinerescaneado',
            name='alerta',
        ),
        migrations.RemoveField(
            model_name='conteinerescaneado',
            name='login',
        ),
        migrations.AddField(
            model_name='conteinerescaneado',
            name='exportado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
