# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0022_auto_20180208_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='exportado',
            field=models.BooleanField(default=False),
        ),
    ]
