# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0023_auto_20180208_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='mascarafiltro',
            field=models.CharField(max_length=20, verbose_name='Mascara no formato " % Y % m % d" mais qualquer literal'),
        ),
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='exportado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fonteimagem',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data do escaneamento retirada do arquivo XML'),
        ),
    ]
