# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0024_auto_20180217_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteinerescaneado',
            name='file_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do escaneamento retirada do arquivo XML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conteinerescaneado',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data do escaneamento retirada do arquivo XML'),
        ),
        migrations.AlterField(
            model_name='fonteimagem',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data de registro'),
        ),
    ]
